spring:
  application:
    name: his
    
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: TU_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update


