spring:
  application:
    name: his

  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: raulrm
    password: Martinez5r
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true